apiVersion: v1
kind: Service
metadata:
  name: netcoredemo1-service
  labels:
    app: netcoredemo1
spec:
  type: NodePort
  ports:
  - nodePort : 31000
    port: 80
    protocol: TCP
  selector:
    app: netcoredemo1